version: '3.7'

services:
  nginx-rtmp:
    image: nginx-rtmp
    ports:
      - "1935:1935" # RTMP 推流端口
      - "8080:8080" # HLS 流媒体播放端口
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
      # - ./hls:/tmp/hls # 存放 HLS 分片的目录
      - ./html:/usr/local/nginx/html # 将 html 目录挂载到 NGINX 静态目录
    restart: always
    environment:
      - TZ=Asia/Shanghai # 设置时区，可根据需求调整

  nginx-proxy:
    image: nginx
    ports:
      - "80:80" # 将主机的80端口映射到容器的80端口
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf # 挂载反向代理配置文件
    restart: always
    depends_on:
      - nginx-rtmp